version: '3.8'

services:
  db:
    image: postgres:latest

    volumes:
      - ./data:/var/lib/postgres/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  backend:
    build: ./.
    command: command gunicorn my_site:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"

    volumes:
      - ./static/:/opt/app
volumes:
  data:
  static:
